/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 AboutMeRoomTextured.gltf 
*/

import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/AboutMe_Room/AboutMeRoomTextured.gltf')
  const groupRef = useRef();

  const [rotateForward, setRotateForward] = useState(true);

  // Rotates back and forth showing only the front side
  useFrame(() => {
    if (rotateForward) {
      groupRef.current.rotation.y += 0.0025;

      if (groupRef.current.rotation.y >= Math.PI / 4) {
        // Reached 45 degrees, switch rotation direction
        setRotateForward(false);
      }
    } else {
      groupRef.current.rotation.y -= 0.0025; // Adjust the rotation speed here
      if (groupRef.current.rotation.y <= -Math.PI / 4) {
        // Reached 0 degrees, switch rotation direction
        setRotateForward(true);
      }
    }
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes.Desk.geometry} material={materials.DeskBase} position={[-1.674, 3.517, -7.724]} />
      <mesh geometry={nodes.DeskUpper.geometry} material={materials.DeskUpper} position={[-1.742, 4.398, -8.656]} />
      <mesh geometry={nodes.NightStand.geometry} material={materials.Nightstand} position={[-8.045, 1.122, 0.303]} />
      <group position={[-3.468, 4.91, -8.694]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.MonitorBase} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Screen} />
      </group>
      <group position={[-0.575, 5.318, -8.747]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.MonitorBase} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Screen} />
      </group>
      <mesh geometry={nodes.MonitorStand.geometry} material={materials.MonitorStand} position={[-0.662, 4.414, -8.542]} />
      <group position={[-8.117, 4.38, -1.885]} rotation={[-Math.PI, 1.014, -Math.PI]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.CLA} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.CLASecondary} />
      </group>
      <mesh geometry={nodes.BlindsHolder.geometry} material={materials.BlindHolder} position={[-9.742, 9.153, -2.283]} />
      <mesh geometry={nodes.BlindsHolder001.geometry} material={materials.BlindHolder} position={[-9.742, 9.153, 3.172]} />
      <mesh geometry={nodes.Blinds.geometry} material={materials.Blinds} position={[-9.656, 11.184, 0.394]} />
      <group position={[3.689, 2.346, -8.064]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.BasePC} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.InnerPC} />
        <mesh geometry={nodes.PCRing001.geometry} material={materials['PCRing.001']} position={[0.741, 0.294, 0.779]} />
        <mesh geometry={nodes.PCRing.geometry} material={materials.PCRing} position={[-0.697, 0.294, 0.779]} />
      </group>
      <mesh geometry={nodes.Chair.geometry} material={materials.Chair} position={[-2.461, 2.807, -4.666]} />
      <group position={[-8.1, 3.912, 2.436]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials['PhoneBase.001']} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['PhoneScreen.001']} />
      </group>
      <mesh geometry={nodes.Rug.geometry} material={materials.Rug} position={[-1.383, 0.999, -1.31]} scale={[4.841, 0.158, 4.841]} />
      <mesh geometry={nodes.Suzanne.geometry} material={materials.Monke} position={[-1.597, 6.604, -8.471]} />
      <mesh geometry={nodes.StandingShelf.geometry} material={materials.Shelf} position={[8.547, 1.526, 6.501]} scale={[1, 3.137, 1]} />
      <mesh geometry={nodes.Suzanne001.geometry} material={materials.Monke1} position={[8.643, 5.94, 4.972]} />
      <mesh geometry={nodes.Suzanne002.geometry} material={materials.Monke2} position={[8.643, 5.94, 7.64]} />
      <mesh geometry={nodes.Suzanne003.geometry} material={materials.Monke3} position={[8.643, 1.542, 7.746]} />
      <mesh geometry={nodes.Suzanne004.geometry} material={materials.Monke4} position={[8.643, 1.542, 5.104]} />
      <mesh geometry={nodes.BeanBag.geometry} material={materials.Beanbag} position={[4.63, 2.325, 7.862]} />
      <mesh geometry={nodes.Bed.geometry} material={materials.Bed} position={[-4.777, 2.719, 6.614]} />
      <mesh geometry={nodes.Bedframe.geometry} material={materials.Bedframe} position={[-4.777, 1.774, 6.65]} />
      <mesh geometry={nodes.Pillow.geometry} material={materials.Pillow} position={[-7.452, 3.768, 7.907]} rotation={[0.046, 0.169, 1.285]} />
      <mesh geometry={nodes.Pillow001.geometry} material={materials.Pillow} position={[-7.603, 3.711, 5.522]} rotation={[-0.022, -0.069, 1.241]} />
      <mesh geometry={nodes.OverheadShelf.geometry} material={materials.OverheadShelf} position={[4.732, 10.236, -8.427]} scale={[3.648, 0.247, 1.229]} />
      <group position={[1.469, 11.46, -8.732]} rotation={[0, 0, -0.057]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[1.778, 11.46, -8.732]} rotation={[0, 0, -0.034]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube020_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[2.089, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube021.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube021_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[2.395, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube022_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube022_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[2.705, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube023_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[3.016, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube024_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[3.342, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube025.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube025_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube025_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[3.652, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube026_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[3.963, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube027_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[4.269, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube028_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[4.578, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube029_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[4.889, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube030_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[5.226, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube031_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[5.535, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[5.846, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[6.152, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube034.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube034_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[6.462, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube035_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube035_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[6.773, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube036.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube036_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube036_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[7.07, 11.46, -8.732]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube037_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[7.379, 11.46, -8.732]} rotation={[0, 0, 0.037]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <group position={[7.69, 11.46, -8.732]} rotation={[0, 0, 0.05]} scale={[0.125, 1, 0.697]}>
        <mesh geometry={nodes.Cube039.geometry} material={materials.Switch} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials.SwitchInner} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials.SwitchFrontCover} />
        <mesh geometry={nodes.Cube039_3.geometry} material={materials.SwitchBackCover} />
      </group>
      <mesh geometry={nodes.PHFlag.geometry} material={materials.PHFlag} position={[-9.425, 10.184, 6.623]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.RoomBase} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.RoomFloor} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.RoomWalls} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials.Outdoors} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials.Window} />
    </group>
  )
}

useGLTF.preload('/models/AboutMe_Room/AboutMeRoomTextured.gltf')
