/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 AboutMeRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/AboutMe_Room/AboutMeRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.RoomBase} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.RoomFloor} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.RoomWalls} />
    </group>
  )
}

useGLTF.preload('/models/AboutMe_Room/AboutMeRoom.gltf')
