/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BaseIsoRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BaseIsoRoom(props) {
  const { nodes, materials } = useGLTF('/models/BaseIsoRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-3.5, -0.231, -3.5]} scale={[10, 0.5, 10]} />
    </group>
  )
}

useGLTF.preload('/models/BaseIsoRoom.gltf')
