/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 GeneralDroneController.gltf 
*/

import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Controller/GeneralDroneController.gltf')

  const groupRef = useRef();

  const [rotateForward, setRotateForward] = useState(true);

  // Rotates back and forth showing only the front side
  useFrame(() => {
    if (rotateForward) {
      groupRef.current.rotation.y += 0.0025;

      if (groupRef.current.rotation.y >= Math.PI / 4) {
        // Reached 45 degrees, switch rotation direction
        setRotateForward(false);
      }
    } else {
      groupRef.current.rotation.y -= 0.0025; // Adjust the rotation speed here
      if (groupRef.current.rotation.y <= -Math.PI / 4) {
        // Reached 0 degrees, switch rotation direction
        setRotateForward(true);
      }
    }
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Primary} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Secondary} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Accent} />
        <group position={[-1.622, 1.094, 0.25]}>
          <mesh geometry={nodes.Cylinder005.geometry} material={materials.Primary} />
          <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Metal} />
          <mesh geometry={nodes['JoystickController-L'].geometry} material={materials['Metal.002']} />
        </group>
        <group position={[1.622, 1.094, 0.25]}>
          <mesh geometry={nodes.Cylinder004.geometry} material={materials.Primary} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Metal} />
          <mesh geometry={nodes['JoystickController-R'].geometry} material={materials['Metal.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Controller/GeneralDroneController.gltf')
