/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Nick_IsoRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Nick_Room/Nick_IsoRoom.gltf')
  const groupRef = useRef()

  // Looks at mouse
  // useFrame(({ mouse, viewport }) => {
  //   const x = (mouse.x * viewport.width) / 2.5
  //   const y = (mouse.y * viewport.height) / 2.5
  //   groupRef.current.lookAt(x, y, 1)
  // })

  // Rotate based on scroll
  // useFrame(() => {
  //   // Get Scroll position
  //   const scrollTop = window.scrollY;

  //   // Calc rotation based on scroll pos
  //   const rotationSpeed = 0.0005;
  //   const rotationY = scrollTop * rotationSpeed;

  //   if (groupRef.current) {
  //     groupRef.current.rotation.y = rotationY;
  //   }
  // })

  return (
    // Remove groupRef if not used
    <group {...props} dispose={null} ref={groupRef}>
      <group scale={[7, 0.25, 10]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.BaseFloor} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Nick Orange']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Wall} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Ceiling} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.MossWall} />
      </group>
      <group position={[-4.923, 0.454, 9.766]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={7}>
        <mesh geometry={nodes.Text001.geometry} material={materials['Nick Orange']} />
        <mesh geometry={nodes.Text001_1.geometry} material={materials['Text InnerBackdrop']} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials.Light} />
      </group>
      <mesh geometry={nodes.Rug.geometry} material={materials.Rug} position={[1.551, 0.468, 1.885]} scale={[3.694, 0.1, 7.951]} />
    </group>
  )
}

useGLTF.preload('/models/Nick_Room/Nick_IsoRoom.gltf')
