/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Nick_IsoRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Nick_Room/Nick_IsoRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={[7, 0.25, 10]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.BaseFloor} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Nick Orange']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Wall} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Ceiling} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.MossWall} />
      </group>
      <group position={[-4.923, 0.454, 9.766]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={7}>
        <mesh geometry={nodes.Text001.geometry} material={materials['Nick Orange']} />
        <mesh geometry={nodes.Text001_1.geometry} material={materials['Text InnerBackdrop']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Nick_Room/Nick_IsoRoom.gltf')
