name: Deploy React App to GitHub Pages

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

run: npx gh-pages -d build -u "github-actions <github-actions@github.com"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npx gh-pages -d build